### ISSUE TITLE
Level 1 - Players capable of teleporting from Basement to Ground level

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#1]
**Describe the bug**
If a player is on the basement level of the gang hide-out building, they are able to aim the teleportation target onto the floor of the above level (ground level), allowing them to jump levels. 

**Version Found**
Visceral Carnage Playtest Release v0.1 Alpha 

**To Reproduce**
1. Start game.
2. Travel to basement level (use stairs on right side of building to access basement VIP bar section).
3. Angle the control with the teleportation target upwards towards the ceiling until the movement curve ends with the circle target on the floor of the ground level above you. 
4. Action movement.
5. Player is now on the Ground Level. 

**Expected Behaviour**
When the player angles the controller above them towards the ceiling, the option to move/teleport to a location above them (i.e. ground floor) should not become available. 

**Screenshots**
n/a
Teleportation shortcut observed during internal playtesting.

**Desktop (please complete the following information):**
OS: Unreal Engine version 4.27.2

**Additional context**
n/a

**Comment by Accident-Prone** [comment]
Fixed. Solved by adjusting how high the player can teleport (teleporting uses a projectile prediction to see where the teleport ends up at). Gravity for the projectile prediction is now slightly higher (can still travel roughly the same distance, but less height)
