### ISSUE TITLE
Lighting Only Appears One Eye

### ISSUE THREAD

**Issue by OverlordArt** [tyndyrn/Visceral-Carnage_GAME#11]
Technical Issue 

In the VR headset the shadows only appears in one eye and not the other, so it creates a visual that can be somewhat nauseating to look at 

Deklan will have to find a way to fix this issue, not too sure how he will go about this but he is sure that he will be able to find a solution for it

**Comment by Asas621** [comment]
Fixed. Shadow cascade disabled.
