### ISSUE TITLE
Dead enemies obstruct players from accessing objects

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#2]
**Describe the bug**
Dead enemies can prevent players from interacting with guns, and potentially other objects, if the ragdoll body falls directly on top of said weapons/objects. 

**Version Found**
Visceral Carnage Playtest Release v0.1 Alpha 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start game.
2. Kill enemy.
3. Place weapons/objects around the dead enemy, or shuffle a dead enemy onto a weapon/object on the floor using an object in your hand.
4. Drop any weapons/objects in hand(s) to free up said hands.
5. With the dead body blocking your view of the weapon/object (while knowing it is there), try to interact with the weapon/object.
6. Struggle. Object cannot be obtained.

**Expected Behaviour**
Dead enemies do not prevent the player from obtaining weapons/objects. 

**Screenshots**
n/a.
Observed during playtesting.

**Desktop (please complete the following information):**
OS: Unreal Engine version 4.27.2

**Additional context**
Observed during playtesting - players needed to use another object to move the dead enemy aside to access the weapon or melee object. Players are unable to interact with dead enemies without an object in hand (intended feature); this can be a potential problem as used weapons/objects can no longer be interacted with and will leave player at a disadvantage if unable to access the obstructed useable weapon/object. Possible solution: players are able to move dead enemies without the need of an weapon/object in their hand.

**Comment by Accident-Prone** [comment]
Confident this has been fixed. Tried testing after fix implemented and was not able to get this to occur (not that it should have anyway with how the grabbing code is written)
