### ISSUE TITLE
Controls that are accommodating for left-handed players

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#3]
**Type of Feature**
Technical

**Is your feature request related to a problem? Please describe.**
_Observed in the playtesting_
The left-hand controller has the teleportation target which is used for directional movement. A left-handed player was having difficulty navigating as they were holding the gun in their left-hand; it appears were was a conflict between the controls of the gun and teleportation target. They were stuck in a loop trying to get to a location, and failing, for roughly 10 seconds. 

**Describe the solution you’d like**
An option that allows players to select which hand control has the teleportation target and directional movement (able to turn around while stationary). 

**Describe alternatives you’ve considered**
n/a

**Additional context**
n/a

**Comment by Accident-Prone** [comment]
Added new menu option in pause menu to allow for toggle between teleporting with either left hand or right hand. Resets on each new level load currently.
