### ISSUE TITLE
Ranged AI gets stuck

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#4]
**Describe the bug**
Ranged enemy AI was wandering to a location it couldn't get to, causing it to get stuck and not attack player.

**Version Found**
Visceral Carnage Playtest Release v0.1 Alpha

**To Reproduce**
Steps to reproduce the behaviour:
1. Start game
2. Observe range AI's movements.

**Expected Behaviour**
Not get stuck. Should have similar behaviour to melee AI.

**Screenshots**
If applicable, add screenshots to help explain you problem.

**Desktop (please complete the following information):**
OS: Unreal Engine version 4.27.2 

**Additional context**

**Comment by Accident-Prone** [comment]
Fixed in latest commit. Now follows similar behavour to melee AI, but altered for shooting from ranged.
