### ISSUE TITLE
Game Control bug -- desktop controls overriding/removing VR controls

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#6]
**Describe the bug**
"Desktop version and VR version combine"
As quoted by Deklan

**Version Found**
Visceral Carnage Deklan v0.1 Alpha

**To Reproduce**
Steps to reproduce the behaviour:
1. Start game 
2. Select the latest game version
3. When the game spawns in it's only meant to check for VR or desktop, but it recognises both of them and merges. The desktop controls are functional and player in VR is being controlled by the player sitting at the desktop. Only the VR camera controls are functional.

**Expected Behaviour**
Not this. VR player should be able to go into the game and be able to use the controls. Input from the desktop should not influence the gameplay.

**Screenshots**
n/a Was experienced by team members.

**Desktop (please complete the following information):**
OS: Unreal Engine version 4.27.2 

**Additional context**

**Comment by Asas621** [comment]
Solved issue.

**Comment by tyndyrn** [comment]
Thank you! Issue now closed
