### ISSUE TITLE
Enemy ragdolls inflating or deflating on dead

### ISSUE THREAD

**Issue by tyndyrn** [tyndyrn/Visceral-Carnage_GAME#8]
**Describe the bug**
"Currently the character ragdolls Freak out and either get inflated or deflated. Need to fix that." -Deklan

**Version Found**
Visceral Carnage Deklan v0.1 Alpha
[build1.4.txt](https://github.com/tyndyrn/Visceral-Carnage_GAME/blob/main/build1.4.txt)

**To Reproduce**
Steps to reproduce the behaviour: 
_based on what Deklan has said in person_
1. Start game
2. Locate enemy mode
3. Hit and kill enemy
4. Enemy model collapses (rig disappears?) and lightbulb disappears as expected
5. When the enemy model falls it either begins to inflate or deflate. Model deflation as been observed by myself - the figure appears shrivelled and uncanny in appearance. 

**Expected Behaviour**
Enemy model collapses as a ragdoll but shape and volume of the model remains or does not appear to noticeably change.

**Screenshots**
None provided

**Desktop (please complete the following information):**
OS: Unreal Engine version 4.27.2 

**Additional context**

**Comment by Asas621** [comment]
Character deflation now fixed, Updating ragdoll system.

**Comment by OverlordArt** [comment]
This has been observed to be done and will be moved to completed
